### ISSUE TITLE
Zones are empty

### ISSUE THREAD

**Issue by ruudschouten** [TheAppgineer/community_remote#20]
I just tried remote for the first time today, but I can't see any zones.
Is there something I need to set up for this?

**Comment by JanKoudijs** [comment]
What platform are you using? And do you have a Roon system, allowing you to enable the extension using the official Roon Remote?

**Comment by ruudschouten** [comment]
I have the Roon Server running on a separate machine, and I did enable the extension with the Roon Remote.

**Comment by JanKoudijs** [comment]
So the zone button is shown in the lower right corner but the displayed list is empty? Do you run Community Remote on Linux or Windows, maybe the log file can be of help here?

**Comment by ruudschouten** [comment]
Oh damn, I thought I put those in the initial post.
I'm running Fedora 40, with Wayland on KDE Plasma.

Where can I find the logs?

**Comment by JanKoudijs** [comment]
`~/.var/app/com.theappgineer.community_remote/data/community_remote/messages.log`

**Comment by ruudschouten** [comment]
Here's the logs.
[messages.log](https://github.com/user-attachments/files/16440075/messages.log)

I did end up seeing zones now, after I had set up Roon with Wine Bottles. 
But when I launched Community Remote for the first time I had not set up Roon yet, or Roon Bridge.

**Comment by JanKoudijs** [comment]
I see in the logs that there is a `Speakers` zone now. Enabling zones can only be done with the official Roon Remote not with Community Remote. Guess everything is working as expected then, closing the issue.
