### ISSUE TITLE
Add audio format and multiple versions

### ISSUE THREAD

**Issue by benjaminbellamy** [TheAppgineer/community_remote#49]
It would be extra nice if audio format was displayed next to album title (eg. FLAC 192KHz 24bit, DSF DSD64, AAC 44.1KHz 257kbps…) especially when some albums are available in multiple format, as well as file origin (local, Qobuz…).

It would be super extra nice to be able to access alternate versions when several versions are available and grouped for the same album (eg. I have over 10 local versions for The Dark of the Moon, Qobuz has 4 of them).

**Comment by JanKoudijs** [comment]
Community Remote depends on the data that is provided by the Roon Server over the Roon API. Unfortunately the Roon API is pretty limited and provides none of the data listed in your request. Regarding metadata, all that is provided is included in the current version.

As Roon Labs hasn't made any functional change on the Roon API in years, I will close this ticket. It is just very unlikely to happen.
